import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.navbar}>
        <div>Icon</div>
        <div>Title</div>
        <div>
          <h3>Wallets</h3>
          <h3>What is Stews Coin</h3>
          <h3>Get started now</h3>
          <h3>Guide</h3>
          <h3>FAQ</h3>
        </div>
      </div>
    </div>
  )
}
